version: '3.1'

services:

  postgres:
    image: postgres
    container_name: 'postgres'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_network_db
    ports:
      - "6532:5432"

  # TODO: describe docker file for Java RestApi service before ancommenting this block
  # api:
  #   build: ../social-network
  #   container_name: 'api'
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres
  
  ui:
    build: ../GeeksSocialNetworkUI
    container_name: "ui"
    volumes:
      - ../GeeksSocialNetworkUI/src:/usr/src/app/src
    ports:
      - "3000:3000"
    # depends_on:
    #   - api
