version: '3.1'

services:

  postgres:
    image: postgres
    container_name: 'postgres'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_network_db
    ports:
      - "4444:5432"
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  api:
    build: ../social-network
    container_name: 'api'
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  
  ui:
    build: ../GeeksSocialNetworkUI
    container_name: "ui"
    volumes:
      - ../GeeksSocialNetworkUI/src:app/src
    ports:
      - "3000:3000"
    depends_on:
      - api
