version: '3.1'

services:

  postgres:
    image: postgres
    container_name: 'java-postgres'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_network_db
    ports:
      - "5432:5432"

  app:
    build: ../social-network
    container_name: 'java-app'
    ports:
      - "8080:8080"
